### PR TITLE
Adding source code for Go tutorial

### PR DESCRIPTION
**Pull request by chrislovecnm**
This commit includes the source code for the Go
Tutorial that is located on the
github.com/bazel-contrib/SIG-rules-authors github pages web site.

### CODE REVIEW

**Review by cgrindel — APPROVED** [review]

**Comment by chrislovecnm** [comment]
@cgrindel this is read to merge

**Comment by cgrindel** [comment]
@helenalt We would like to merge this PR. Unfortunately, I do not have permission. Could you either give me permission to merge the PR or do the merge for us? Thanks!

**Comment by chrislovecnm** [comment]
cc @bmuschko

**Comment by bmuschko** [comment]
@chrislovecnm Unfortunately, I do not have the permissions to merge a PR either.

**Comment by cgrindel** [comment]
@alexeagle Could you help us get this PR merged?

**Comment by alexeagle** [comment]
From reading the SIG notes it seems like the decision was to host these on the rules instead?

**Comment by chrislovecnm** [comment]
Closing because of https://github.com/bazelbuild/rules_go/pull/3317

**Pull request closed without merging**
